### ISSUE TITLE
ie11 compatibility issue

### ISSUE THREAD

**Issue by wmbstx** [zanfab/gitbook-plugin-flexible-alerts#10]
It seems not work in ie11?

![image](https://user-images.githubusercontent.com/6022880/52994359-402a7e00-3452-11e9-9867-0994ce840113.png)

**Comment by zanfab** [comment]
@wmbstx
I will test it using IE11 and provide a fix if there is a respective issue.

**Comment by zanfab** [comment]
Fixed in release 1.0.2
